### ISSUE TITLE
the Tcpstream won't be close after drop the Tcpstream

### ISSUE THREAD

**Issue by Sherlock-Holo** [ringbahn/ringbahn#46]
in this [code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f67da34e2adc1d34468367d29099b2bb), when run the test and see the `/proc/{pid}/fd`, we can see there is no fd which type is `socket`. Press enter to make program continue running until sleep, and see the `/proc/{pid}/fd` again, we can see there is a fd like `4 -> 'socket:[13186835]'`.

In normal the Tcpstream should be closed but it doesn't, and I find the Tcpstream doesn't implement the `Drop`

**Comment by withoutboats** [comment]
This is because of the lack of async drop. The way to close the Tcpstream is to call the `close` method from `futures::io::AsyncWriteExt` and awaiting the returned future.

We could do something cleverer here, like do a blocking drop if you haven't closed the tcpstream when its dropped.

**Comment by Sherlock-Holo** [comment]
I think we can close the fd directly when drop the TcpStrean, any pending io operation in io_uring should be failed, we can ignore those errors

**Comment by withoutboats** [comment]
I also think we can close it with a `libc::close`, but I'm not sure if we *should*. In any event we need to document that a correct implementation should explicitly close its handles before dropping them.
